default_language_version:
  python: python3.13

repos:
- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.8.17
  hooks:
    - id: uv-lock

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.13.0
  hooks:
    - id: ruff
      args: ["--fix", "--exit-non-zero-on-fix"]

- repo: https://github.com/psf/black
  rev: 25.1.0
  hooks:
    - id: black

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.18.1
  hooks:
    - id: mypy
      stages: [manual]
      args: ["src"]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
      args: ["--markdown-linebreak-ext=md,mdx"]
    - id: detect-private-key
    - id: mixed-line-ending
      args: ["--fix=lf"]
    - id: check-ast
    - id: check-yaml
    - id: check-toml
    - id: check-json
    - id: debug-statements
    - id: check-merge-conflict
    - id: check-added-large-files
      args: ["--maxkb=500"]
    - id: requirements-txt-fixer
