name: ci
on:
  push:
    branches: [main]
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6
        with:
          version: latest

      - run: uv python install
      - run: uv sync --locked
      - run: uv run pre-commit run --all-files --hook-stage manual --show-diff-on-failure
      - run: uv run pytest -q
